version: '3'

services:
  algo_container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./algo_container:/algo_container
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true