version: '3'

services:
  algo_container:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./algo_container:/algo_container
    ports:
      - "5000:5000"
  ui_container:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./ui_container:/ui_container
    ports:
      - "5001:5001"
    depends_on:
      - algo_container